#!/bin/sh

LISTFILE=$1
HOSTPORT=${2:-127.0.0.1:8000}
FIFO=${3:-/tmp/fnord}
export GABBI_FORCE_COLOR=True
export GABBI_HEADER_COLOR=green
export GABBI_REQUEST_COLOR=red
export GABBI_STATUS_COLOR=red

function wait_one_key() {
    read -n 1 -s
}

wait_one_key
(for file in $(cat $LISTFILE); do
    clear
    clear >${FIFO}
    echo $file >${FIFO}
    cat $file |pygmentize -lyaml -f terminal -O bg=light >${FIFO}
    (echo ; echo) >${FIFO}
    gabbi-run $HOSTPORT < $file |less -eR
done) 2>${FIFO}

clear
