#!/bin/sh

LISTFILE=$1
HOSTPORT=${2:-localhost:8000}

function wait_one_key() {
    read -n 1 -s
}

for file in $(cat $LISTFILE); do
    clear
    cat $file
    wait_one_key
    gabbi-run $HOSTPORT 2>&1 < $file |less -e
done

clear
