#!/bin/sh

LISTFILE=${1:-gab}
HOSTPORT=${2:-localhost:8000}
FIFO=${3:-/tmp/fnord}

mkfifo $FIFO || true

tmux new-session -d "./grunner $LISTFILE $HOSTPORT $FIFO"
tmux split-window -h "cat $FIFO"
tmux selectw -t 0 
tmux selectp -t 0
tmux -2 attach-session -d
